name: Tests CI

# Controls when the workflow will run
on: [push, workflow_dispatch]

env:
  SOME_VAR: ${{ secrets.NEXT_PUBLIC_SOME_VAR }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  static-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
  unit-integration-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run jest
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm test
